// Re-export pages for cleaner imports
export { default as DashboardPage } from './DashboardPage'
export { default as ProjectsListPage } from './ProjectsListPage'
export { default as ProjectDetailPage } from './ProjectDetailPage'
export { default as CostsPage } from './CostsPage'
export { default as ConfigsListPage } from './ConfigsListPage'
export { default as ConfigCreatePage } from './ConfigCreatePage'
export { default as AlertsPage } from './AlertsPage'
export { default as SettingsPage } from './SettingsPage'
export { default as RunHistoryPage } from './RunHistoryPage'
export { default as DataSourcesPage } from './DataSourcesPage'
